"""Create NEXT_SQL_COMPLEX_MAP for SQL conversion supplemental mapping rules.

Run:
  python scripts/create_sql_complex_map_table.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

from scripts._bootstrap import ROOT_DIR
from server.services.sql.db_runtime import get_connection


load_dotenv(ROOT_DIR / ".env")


DDL = """
CREATE TABLE NEXT_SQL_COMPLEX_MAP (
    MAP_ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    USE_YN       CHAR(1) DEFAULT 'Y' NOT NULL,
    FR_TABLE     VARCHAR2(128) NOT NULL,
    FR_COL       CLOB,
    TO_TABLE     VARCHAR2(128) NOT NULL,
    TO_COL       CLOB,
    DESCRIPTION  CLOB,
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPD_TS       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NEXT_SQL_COMPLEX_MAP PRIMARY KEY (MAP_ID),
    CONSTRAINT CK_NEXT_SQL_COMPLEX_MAP_USE_YN CHECK (USE_YN IN ('Y', 'N'))
)
"""


INDEX_DDL = """
CREATE INDEX IX_NEXT_SQL_COMPLEX_MAP_01
    ON NEXT_SQL_COMPLEX_MAP (USE_YN, FR_TABLE)
"""


TRIGGER_DDL = """
CREATE OR REPLACE TRIGGER TRG_NEXT_SQL_COMPLEX_MAP_UPD
BEFORE UPDATE ON NEXT_SQL_COMPLEX_MAP
FOR EACH ROW
BEGIN
    :NEW.UPD_TS := SYSTIMESTAMP;
END;
"""


COMMENTS = [
    "COMMENT ON TABLE NEXT_SQL_COMPLEX_MAP IS 'SQL conversion supplemental mapping rules'",
    "COMMENT ON COLUMN NEXT_SQL_COMPLEX_MAP.MAP_ID IS 'Auto generated mapping rule id'",
    "COMMENT ON COLUMN NEXT_SQL_COMPLEX_MAP.USE_YN IS 'Y means active mapping rule'",
    "COMMENT ON COLUMN NEXT_SQL_COMPLEX_MAP.FR_TABLE IS 'Source table key matched from NEXT_SQL_INFO.TARGET_TABLE'",
    "COMMENT ON COLUMN NEXT_SQL_COMPLEX_MAP.FR_COL IS 'Source column name or source SQL pattern used for RAG matching'",
    "COMMENT ON COLUMN NEXT_SQL_COMPLEX_MAP.TO_TABLE IS 'TO-BE table name'",
    "COMMENT ON COLUMN NEXT_SQL_COMPLEX_MAP.TO_COL IS 'TO-BE column name or converted SQL pattern'",
    "COMMENT ON COLUMN NEXT_SQL_COMPLEX_MAP.DESCRIPTION IS 'Meaning, condition, hierarchy, or transformation explanation'",
]


def table_exists(cur, table_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = :1",
        (table_name.upper(),),
    )
    return int(cur.fetchone()[0] or 0) > 0


def index_exists(cur, index_name: str) -> bool:
    cur.execute(
        "SELECT COUNT(*) FROM USER_INDEXES WHERE INDEX_NAME = :1",
        (index_name.upper(),),
    )
    return int(cur.fetchone()[0] or 0) > 0


def main() -> None:
    with get_connection() as conn:
        cur = conn.cursor()
        if table_exists(cur, "NEXT_SQL_COMPLEX_MAP"):
            print("NEXT_SQL_COMPLEX_MAP already exists. Skipping table creation.")
        else:
            cur.execute(DDL)
            print("NEXT_SQL_COMPLEX_MAP created.")

        if index_exists(cur, "IX_NEXT_SQL_COMPLEX_MAP_01"):
            print("IX_NEXT_SQL_COMPLEX_MAP_01 already exists. Skipping index creation.")
        else:
            cur.execute(INDEX_DDL)
            print("IX_NEXT_SQL_COMPLEX_MAP_01 created.")

        cur.execute(TRIGGER_DDL)
        print("TRG_NEXT_SQL_COMPLEX_MAP_UPD created or replaced.")

        for statement in COMMENTS:
            cur.execute(statement)

        conn.commit()
        print("NEXT_SQL_COMPLEX_MAP DDL setup complete.")


if __name__ == "__main__":
    main()
